### PR TITLE
Fork

### PR DESCRIPTION
**Pull request by rossabaker**
This is the internal fork of parboiled2, spun off to a separate repo because it rarely changes and is unlike the rest of our build.

Tracks the release-2.1 branch of the upstream repo, so it should be easy to merge any future improvements as needed.

### CODE REVIEW

**Comment by rossabaker** [comment]
I'm glad you asked, because the entire point is to not, and I failed miserably. 🤣

**Comment by aeons** [comment]
Is this one good to go then?

**Comment by rossabaker** [comment]
I think so, but I thought it was the first time and @ChristopherDavenport saved me from terrible embarrassment. :)

**Comment by ChristopherDavenport** [comment]
Two secs.

**Comment by rossabaker** [comment]
https://github.com/http4s/http4s/pull/1415 passing locally is my evidence that we don't use the red blobs.

**Comment by ChristopherDavenport** [comment]
Good enough for me. 

YOLO Parboiled segregation

**Pull request merged**
